[project]
name = "attendance-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.10.17"
dependencies = [
    "opencv-python>=4.11.0.86",
    "pyqt6>=6.9.0",
]
